added roles impl for accessing methods
VdBondarev/book_store pull request #11
Opened 2024-02-23 15:43 UTC by VdBondarev

2024-02-23 19:52 UTC, okuzan requested changes
Good job so far

2024-02-23 19:52 UTC, okuzan commented on src/main/java/mate/academy/config/SecurityConfig.java
> +                                .permitAll()
combine into one

2024-02-23 19:52 UTC, okuzan commented on src/main/java/mate/academy/controller/UserController.java
> +    @GetMapping("/find-all")
`/find-all` doesn't follow RESTful best practices as it includes an action (find-all) which is more RPC-like (Remote Procedure Call) rather than resource-oriented. In REST the action should be implied by the HTTP method, and the URL should represent the resource - GET /users would be fine
```suggestion
    @GetMapping
```

2024-02-23 19:52 UTC, okuzan commented on src/main/java/mate/academy/model/User.java
>  @Where(clause = "is_deleted=false")
```suggestion
@SQLDelete(sql = "UPDATE users SET is_deleted = TRUE WHERE id = ?")
@Where(clause = "is_deleted = FALSE")
```

2024-02-23 19:52 UTC, okuzan commented on src/main/java/mate/academy/repository/book/BookRepository.java
> +    void updateBook(@Param("id") Long id, @Param("requestDto") CreateBookRequestDto requestDto);
there's more traditional approach to this 
1. get DTO
2. set ID for it
3. map to entity
4. save this entity
5. voila, entity updated
6. map back to DTO and return state of updated entity

If we `save()` entity which already has ID, we won't create new entity, we will update existing one, assuming it exists

2024-02-23 19:52 UTC, okuzan commented on src/main/resources/db/changelog/changes/03-create-roles-table.yaml
> +            tableName: roles
```suggestion
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(255)
                  constraints:
                    unique: true
                    nullable: false
      rollback:
        - dropTable:
            tableName: roles
            
```
don't forget one empty line at the EOF

2024-02-23 19:52 UTC, okuzan commented on src/main/resources/db/changelog/changes/04-create-user_roles-table.yaml
> +            tableName: user_roles
```suggestion
            tableName: user_roles
            
```

2024-02-23 19:52 UTC, okuzan commented on src/main/resources/db/changelog/changes/05-insert-roles-user-admin.yaml
> +                  { name: name, value: "ROLE_USER" }
```suggestion
                  { name: name, value: "ROLE_USER" }
                  
```

2024-02-23 19:52 UTC, okuzan commented on src/main/resources/db/changelog/changes/06-insert-user-admin.yaml
> +                  { name: last_name, value: "Bondarev" }
```suggestion
                  { name: last_name, value: "Bondarev" }
                  
```

2024-02-23 19:52 UTC, okuzan commented on src/main/resources/db/changelog/changes/07-insert-user-roles-admin.yaml
> +                  { name: role_id, value: "2" }
```suggestion
                  { name: role_id, value: "2" }
                  
```

2024-02-23 20:06 UTC, VdBondarev commented on src/main/resources/db/changelog/changes/03-create-roles-table.yaml
> +            tableName: roles
can you explain to me why we need an empty line at the end of file? Or is it just that stuff you always should do without explanation?

2024-02-23 20:13 UTC, VdBondarev commented on src/main/java/mate/academy/config/SecurityConfig.java
> +                                .permitAll()
how?

2024-02-24 14:55 UTC, olekskov requested changes

2024-02-24 14:55 UTC, olekskov commented on src/main/java/mate/academy/config/SecurityConfig.java
> +                                .permitAll()
should be something like that
```suggestion
                                .requestMatchers("/api/authentication/**", "/error", "/swagger-ui/**")
                                .permitAll()
```

2024-02-24 14:55 UTC, olekskov commented on src/main/java/mate/academy/service/user/UserServiceImpl.java
> +    private User createUserFromRequestDto(Role.RoleName roleName,
private methods should be placed after public to have main official logic first

2024-02-24 14:55 UTC, olekskov commented on src/main/java/mate/academy/dto/book/BookUpdateDto.java
> +// so you can only pass an only param and others will be as they were before
Please format as JavaDoc if you wish to leave some clarifying information

2024-02-24 14:55 UTC, olekskov commented on src/main/java/mate/academy/mapper/BookMapper.java
> +    }
Not fully sure but something like that may work, please recheck
```suggestion
    Book toModel(@MappingTarget Book book, BookUpdateDto requestDto);
```

2024-02-24 15:33 UTC, VdBondarev commented on src/main/java/mate/academy/mapper/BookMapper.java
> +    }
I checked and this way it doesn't work (console writes that params can't be null when mapping to dto from model that was mapped the way you propose (as I understand, null fields get set to book too))

2024-02-24 16:35 UTC, olekskov approved these changes

2024-02-24 16:50 UTC, merged