Add impl for shopping cart, but it doesn't work any way I change it. Can you tell me what can be wrong? Maybe it is related to getting current user?
VdBondarev/book_store pull request #17
Opened 2024-02-26 12:12 UTC by VdBondarev

2024-02-27 14:25 UTC, okuzan requested changes
GJ

2024-02-27 14:25 UTC, okuzan commented on src/main/java/mate/academy/controller/ShoppingCartController.java
> +@RequestMapping(value = "/api/cart")
move /api to server.servlet.context-path in properties

2024-02-27 14:25 UTC, okuzan commented on src/main/java/mate/academy/mapper/CartItemMapper.java
> +    }
use mapstruct for mapping
use default @AfterMapping methods if needed

2024-02-27 14:25 UTC, okuzan commented on src/main/java/mate/academy/service/shopping/cart/ShoppingCartServiceImpl.java
> +            return shoppingCartMapper.toDto(shoppingCartRepository.save(shoppingCart));
try to delegate some of this logic to private methods, method looks bulky

2024-02-28 10:26 UTC, kozhukhovsky approved these changes

2024-02-28 14:43 UTC, merged